
package com.aws.p218nfemitida.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSConsultarColdSincronoSoap", targetNamespace = "http://nddigital.com.br/eForms/webservices")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSConsultarColdSincronoSoap {


    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarDocumento", action = "http://nddigital.com.br/eForms/webservices/ConsultarDocumento")
    @WebResult(name = "ConsultarDocumentoResult", targetNamespace = "http://nddigital.com.br/eForms/webservices")
    @RequestWrapper(localName = "ConsultarDocumento", targetNamespace = "http://nddigital.com.br/eForms/webservices", className = "com.aws.p218nfemitida.soap.ConsultarDocumento")
    @ResponseWrapper(localName = "ConsultarDocumentoResponse", targetNamespace = "http://nddigital.com.br/eForms/webservices", className = "com.aws.p218nfemitida.soap.ConsultarDocumentoResponse")
    public String consultarDocumento(
        @WebParam(name = "xml", targetNamespace = "http://nddigital.com.br/eForms/webservices")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarStatusSincrono", action = "http://nddigital.com.br/eForms/webservices/ConsultarStatusSincrono")
    @WebResult(name = "ConsultarStatusSincronoResult", targetNamespace = "http://nddigital.com.br/eForms/webservices")
    @RequestWrapper(localName = "ConsultarStatusSincrono", targetNamespace = "http://nddigital.com.br/eForms/webservices", className = "com.aws.p218nfemitida.soap.ConsultarStatusSincrono")
    @ResponseWrapper(localName = "ConsultarStatusSincronoResponse", targetNamespace = "http://nddigital.com.br/eForms/webservices", className = "com.aws.p218nfemitida.soap.ConsultarStatusSincronoResponse")
    public String consultarStatusSincrono(
        @WebParam(name = "xml", targetNamespace = "http://nddigital.com.br/eForms/webservices")
        String xml);

}
